name: Deploy Site

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish_site.yml
      - .snippets/**
      - docs/**
      - mkdocs.yml
      - requirements.txt

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout Repositoryy
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -r requirements.txt
      - name: Build Site
        run: mkdocs build
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        id: deploy
